---@class Emoji
---@field label string
---@field text string
---@field text_edit string

local url = "https://unicode.org/emoji/charts-17.0/emoji-ordering.txt"
local tmp = "/tmp/emoji-ordering.txt"
local output_file = "lua/blink-cmp-emoji/glyphs.lua"

---@type table<string, string>
local transliterations = {
    ["à"] = "a",
    ["á"] = "a",
    ["â"] = "a",
    ["ã"] = "a",
    ["ä"] = "a",
    ["å"] = "a",
    ["è"] = "e",
    ["é"] = "e",
    ["ê"] = "e",
    ["ë"] = "e",
    ["ì"] = "i",
    ["í"] = "i",
    ["î"] = "i",
    ["ï"] = "i",
    ["ò"] = "o",
    ["ó"] = "o",
    ["ô"] = "o",
    ["õ"] = "o",
    ["ö"] = "o",
    ["ù"] = "u",
    ["ú"] = "u",
    ["û"] = "u",
    ["ü"] = "u",
    ["ý"] = "y",
    ["ÿ"] = "y",
    ["ñ"] = "n",
    ["ç"] = "c",
}

---@param input string
---@return string
local function normalize(input)
    for accented, plain in pairs(transliterations) do
        input = input:gsub(accented, plain)
    end
    return input
end

---@param description string
---@return string
local function make_label(description)
    local normalized = normalize(description)
        :gsub("[ %-]", "_")
        :gsub("[%.&:,']", "")
        :gsub("\u{201C}", "")
        :gsub("\u{201D}", "")
        :gsub("_+", "_")
        :lower()
    return ":" .. normalized .. ":"
end

---@param source string
---@param destination string
local function download_file(source, destination)
    local ok = os.execute(string.format("curl --silent --output %s '%s'", destination, source))
    if not ok then
        error("Failed to download: " .. source)
    end
    -- local convert_ok = os.execute(string.format(
    --     "iconv -f latin1 -t utf-8 %s -o %s",
    --     destination, destination
    -- ))
    -- if not convert_ok then
    --     error("Failed to convert encoding: " .. destination)
    -- end
end



---@param path string
---@return Emoji[]
local function parse(path)
    local emoji_file = io.open(path, "r")
    if not emoji_file then
        error("Failed to open file: " .. path)
    end

    ---@type Emoji[]
    local emojis = {}
    for line in emoji_file:lines() do
        if not line:match("^%s*#") and line ~= "" then
            local codepoints, emoji, description = line:match("^(U%+[^;]+);%s+[%d.]+%s+#%s+(%S+)%s+(.+)$")
            if codepoints and description then
                --local emoji = codepoints_to_str(codepoints)
                -- ignore Zero Width Joiner sequences, as they are often variants of the same emoji and not all platforms support them
                if not codepoints:find("U%+200D") then
                    local label = make_label(description)
                    table.insert(emojis, {
                        label = emoji .. " " .. label,
                        text = emoji,
                        text_edit = label,
                    })
                end
            end
        end
    end

    emoji_file:close()
    return emojis
end

---@param emojis Emoji[]
---@param path string
local function write_lua(emojis, path)
    local out_file = io.open(path, "w")
    if not out_file then
        error("Failed to open output file: " .. path)
    end

    out_file:write("-- Auto-generated by scripts/generate.lua\n")
    out_file:write("return {\n")

    for _, emoji in ipairs(emojis) do
        out_file:write(
            string.format('    { label = "%s", filterText="%s", insertText="%s", textEdit = { newText = "%s" } },\n',
                emoji.label,
                emoji.text_edit,
                emoji.text,
                emoji.text_edit
            )
        )
    end

    out_file:write("}\n")
    out_file:close()
end

download_file(url, tmp)

local emojis = parse(tmp)

write_lua(emojis, output_file)
print(string.format("Done. Written %d emojis.", #emojis))
